name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-test-publish:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH="${{ github.workspace }}"
        export TESTING=1
        pytest

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:${IMAGE_TAG} \
                     -t ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:${IMAGE_TAG}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fruits-api:latest
